name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: Run Setup
        run: bin/setup

      - name: Run Tests
        run: bin/test ci
